name: Publish release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
